// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVD1HLjvAay7ohihjNgDIt-hqNCV7RFtk',
    appId: '1:1086423670194:web:8cacdfe70eb85b9a3218ab',
    messagingSenderId: '1086423670194',
    projectId: 'crwn-clothing-3061a',
    authDomain: 'crwn-clothing-3061a.firebaseapp.com',
    storageBucket: 'crwn-clothing-3061a.appspot.com',
    measurementId: 'G-RWQ23LFE92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8yI0M9mSBt_DNXyZdOsy64QIYGnI9UNM',
    appId: '1:1086423670194:android:188ed6bf676552443218ab',
    messagingSenderId: '1086423670194',
    projectId: 'crwn-clothing-3061a',
    storageBucket: 'crwn-clothing-3061a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4yGvLutUHTJ-eUvye6oBdHlLyWxTQfpk',
    appId: '1:1086423670194:ios:7c24f2909de4cb633218ab',
    messagingSenderId: '1086423670194',
    projectId: 'crwn-clothing-3061a',
    storageBucket: 'crwn-clothing-3061a.appspot.com',
    iosClientId:
        '1086423670194-lqrspsdvdl8fhvn845n64ac1fk5rtuu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.appazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4yGvLutUHTJ-eUvye6oBdHlLyWxTQfpk',
    appId: '1:1086423670194:ios:1ce51e3a732df9a63218ab',
    messagingSenderId: '1086423670194',
    projectId: 'crwn-clothing-3061a',
    storageBucket: 'crwn-clothing-3061a.appspot.com',
    iosClientId:
        '1086423670194-390pp78n6g57k3ln4dqg2rdn484iv77d.apps.googleusercontent.com',
    iosBundleId: 'com.example.appazon.RunnerTests',
  );
}
